/*
 * drakos - An x64 UEFI gaming OS inspired by the architecture and user experience of modern consoles.
 * Copyright (C) 2026 fmdxp
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


#pragma once

#include <stdint.h>
#include "module.hpp"
#include "font.hpp"

class VGA : public KernelModule {
public:
    bool start() override;
    void stop() override;
    const char* get_name() const override;

    void write_char(char c);        // Single char printing
    void write(const char* str);    // String printing

    void scroll();
    void draw_cursor();
    void clear_cursor();
    void clear_screen();

    bool selectBitmapFont(const BitmapFont* font);

private:
    uint32_t* m_framebuffer;
    uint64_t  m_width;
    uint64_t  m_height;
    uint64_t  m_pitch; // Bytes per row (important!)

    uint32_t  m_cursor_x;
    uint32_t  m_cursor_y;

    uint32_t  m_fg_color;
    uint32_t  m_bg_color;

    const BitmapFont* m_font;

    // Helper method to draw a single pixel
    void put_pixel(uint32_t x, uint32_t y, uint32_t color);
};

// Expose the global VGA instance
extern VGA* g_vga;

// The font generated by objcopy
extern "C" const uint8_t _binary_src_fonts_Lat2_Terminus16_psf_start[];